# Generated by Django 3.2.13 on 2022-10-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='thumbnail',
            new_name='profile_image',
        ),
    ]
