# Generated by Django 3.2.13 on 2022-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='catagory',
            field=models.TextField(choices=[('해외영화', '해외영화'), ('국내영화', '국내영화')], default='국내영화'),
        ),
    ]
